name: Checkly Tags Validation

on:
  pull_request:
    branches:
      - master
    paths:
      - "checkly.config.ts"
      - "checkly.config.js"
      - "synthetics/**"

jobs:
  validate-checkly-tags:
    name: Validate Checkly Tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: Appcharge/github-actions-warehouse/.github/actions/synthetics/tags-validation@master
        with:
          NPM_TOKEN: ${{ secrets.DEVOPS_SA_PAT }}
